language: julia
os:
  - osx
  - linux
julia:
  - 0.7
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
before_install:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'ENV["PYTHON"]=""; Pkg.build("ExcelReaders")'
  - julia --check-bounds=yes -e 'Pkg.test("ExcelReaders", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("ExcelReaders")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("ExcelReaders")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
